### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by juanibiapina** [pote/gpm#58]
Since you're using the `-d` flag on `go get` (https://github.com/pote/gpm/blob/master/bin/gpm#L49), downloaded packages are not installed by default.

I've seem there is a plugin for "prebuilding" dependencies, and what it does is to call `go install` on each dependency.

Why not just add another loop around this line (https://github.com/pote/gpm/blob/master/bin/gpm#L69) to call go install for each dependency?

It seems like something you would expect from a dependency manager, instead of having to install a plugin and remember to run another command every time.

Any thoughts?

**Comment by pote** [comment]
Yeah, that makes sense.

Historically we were not installing packages simply because of simplicity of code: there was only one loop in the original implementation and we wanted to keep it that way while it was possible, in the end it turned out to be a bad idea so we moved on from that stance.

I'd be open to add this change or accepting a pull request that does it! Incidentally this might be the first instance of functionality created on a plugin and merged into core, so that's exiting ^_^

**Comment by pote** [comment]
#61 Introduces this change, closing the issue!
