### ISSUE TITLE
Easier installation and plugin management

### ISSUE THREAD

**Issue by pksunkara** [pote/gpm#72]
In my opinion, gpm is being too reliant on home-brew for distributing itself to users. If gpm is rewritten in `go`, we can distribute it easily as a binary. And also a lot of other features can be added easily.

I am pledging my time to do this alongside with you.

**Comment by pote** [comment]
I agree that we shouldn't rely too much on homebrew, particularly since it's an OSX-only solution. 

We've had this complaint before, so I just pushed a one liner that installs gpm without the need for external tools (well, `wget`, but who doesn't have that?) , you can see it [in the readme](https://github.com/pote/gpm#manually-with-a-one-liner), but it's pretty straightforward:

```bash
$ wget https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm && chmod +x gpm && sudo mv gpm /usr/local/bin
```

Having said that, I don't oppose the idea of a rewrite in Go, I just pushed a branch `go-rewrite` so we can all work on it collaboratively and see what comes off it. it's important to note though that gpm having few features is intentional: we aim to keep the codebase understandable and simple so gpm never gets in anyone's way or solves more problems than it needs to.

Anyway, the branch is there, so everyone is welcome to send PRs to it, obviously as this is an experimental branch (and will continue to be for the foreseeable future) I'll be much more forgiving than usual in accepting pull requests initially, so knock yourself out! :D

Also: thank you for taking the time to help gpm improve, I really appreciate it :smile:

**Comment by pote** [comment]
(Offtopic: do you guys use gpm at Apiary? Would love to add your logo to [this thread](https://github.com/pote/gpm/issues/49) for the new gpm website, if you guys feel up to it :smile: )

**Comment by pksunkara** [comment]
Hey @pote 

1. We don't use go at Apiary. I use it for some personal projects and am planning on making a web framework in go in my free time.
2. Thanks for agreeing with regarding the rewrite in go. Let's make `gpm` the best package manager for golang.
3. I agree that we should have as few features as possible, but I also think that we should have all the features that makes the package managing work easier for developers. For example, there is no command to generate the Godeps from the current checked out revisions.
4. Before we start re-writing this in golang, I think it is beneficial for us if we can think hard and list all the requirements and use cases for GPM and it's features.

**Comment by foca** [comment]
> I agree that we should have as few features as possible, but I also think that we should have all the features that makes the package managing work easier for developers. For example, there is no command to generate the Godeps from the current checked out revisions.

There's A Plugin For That™: https://github.com/pote/gpm-bootstrap :stuck_out_tongue:

**Comment by pksunkara** [comment]
I know. But don't you agree that it should one of the core features?

**Comment by pote** [comment]
The plugin should definitely be improved though. :P

**Comment by pksunkara** [comment]
## Design Document

This is a design document on the new rewrite of `gpm` to golang. The main concept behind `gpm` as a package manager is **Revision Locking** (RL).

Revision Locking creates a dependency file that references specific commits in the different version control systems the code is located in. Then the RL tool is used to get, build and install your project. Advantage of revision locking compared to **Vendoring** is that your project repository continues to only contain the specific project code.

#### Audience
The document defines two main consumers of a `gpm`. Briefly, these are:
* A developer of a Go Package or set of Packages (Library)
* A developer of a Go Application that consumes Go code written by others.

#### Actions
These are the commands that `gpm` needs to support:

###### Fetch
This command should read the `Godeps` file and fetch all the dependencies listed inside them using the command `go get`. After fetching all of them, the tool should go into each dependency which was fetched and checkout the respective revision which was given earlier.

###### Generate
**NOTE: THIS IS STILL WIP. NEED TO THINK A BIT MORE**

This command should generate the `Godeps` file using the following logic.

1. List all the top-level dependencies of the current code and fetch them.
2. For each dependency, check for `Godeps` file.

#### Code Organization
Each action in `gpm` should be a function on its own in the package `github.com/pote/gpm/gpm` taking options as arguments. Once that is done, the `main.go` in package `github.com/pote/gpm` should be just a wrapper that converts the command line string to execute one of the above actions. This way, the `gpm` can be run programmatically.
